### ISSUE TITLE
@todo tasks, before next update

### ISSUE THREAD

**Issue by mebjas** [mebjas/facebook-chat-customiser#1]
- [x] Remove that option to share like that
- [x] Check why the options doesn't always appear in the setting menu
- [ ] **feature:** option to change the settings individually
- [x] better option of sharing?
